const skills = [
  // Surface
  {
    attributes: {
      rotate: 'BS',
      board: 'TS',
      jump: false,
      degree: 90,
    },
    category: 'surface',
    level: 2,
    name: 'Powerslide',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: '9MbJhPQp740',
        start: 43,
        title: 'Wakeboard Anfänger Trick lernen - Powerslide GER',
        lang: 'de',
        channel: 'how2wake',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'r0fSSITze4',
        start: 0,
        title: 'Wakeboard Beginner Trick Powerslide ENG',
        lang: 'de',
        channel: 'how2wake',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'ju19fmZAvHQ',
        start: 0,
        title: 'Powerslide & Surface BS 180 Wakeboard Tutorial [GER]',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'NtPMRG16TJ0',
        start: 0,
        title: 'Powerslide & Surface BS 180 Wakeboard Tutorial [ENG]',
        lang: 'en',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: 'BS',
      board: 'HS',
      jump: false,
      degree: 90,
    },
    category: 'surface',
    level: 4,
    name: 'Spray Tricks',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: '42AEewWlTxg',
        start: 0,
        title: 'Spray Tricks Wakeboard Tutorial [GER]',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: '9EwQwkKD2jE',
        start: 0,
        title: 'Spray Tricks Wakeboard Tutorial [ENG]',
        lang: 'en',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: 'FS',
      board: 'HS',
      jump: false,
      degree: 180,
    },
    category: 'surface',
    level: 1,
    name: 'Surface FS 180',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'hik4ARmn6hQ',
        start: 0,
        title: 'Sideslide & Surface FS 180 Wakeboard Tutorial [GER]',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'CTV5YOnl-fU',
        start: 0,
        title: 'Sideslide & Surface HS FS 180 Wakeboard Tutorial [ENG]',
        lang: 'en',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: 'BS',
      board: 'TS',
      jump: false,
      degree: 180,
    },
    category: 'surface',
    level: 3,
    name: 'Surface BS 180',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'ju19fmZAvHQ',
        start: 0,
        title: 'Powerslide & Surface BS 180 Wakeboard Tutorial [GER]',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'CTV5YOnl-fU',
        start: 0,
        title: 'Trockenübungen | BS 180 | BS Outs | Blind Landungen',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'NtPMRG16TJ0',
        start: 0,
        title: 'Powerslide & Surface BS 180 Wakeboard Tutorial [ENG]',
        lang: 'en',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: 'FS',
      board: 'HS',
      jump: false,
      degree: 360,
    },
    category: 'surface',
    level: 4,
    name: 'Surface FS 360',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'tTaxdn7vOos',
        start: 0,
        title: 'Surface FS & BS 360 Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: 'BS',
      board: 'HS',
      jump: false,
      degree: 360,
    },
    category: 'surface',
    level: 4,
    name: 'Surface BS 360',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'tTaxdn7vOos',
        start: 0,
        title: 'Surface FS & BS 360 Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
    ],
  },

  // Start
  {
    attributes: {
      rotate: '',
      board: '',
      jump: false,
      degree: 0,
    },
    category: 'start',
    level: 1,
    name: 'Wasserstart',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'WYEgCXNBk_M',
        start: 19,
        title: 'Waterstart Boat Getting Up...Wakeboarding',
        lang: 'de',
        channel: 'WaketownBerlin',
      },
    ],
  },
  {
    attributes: {
      rotate: '',
      board: '',
      jump: false,
      degree: 0,
    },
    category: 'start',
    level: 2,
    name: 'Sitz Start',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'S0WrghXAtTM',
        start: 0,
        title: 'Wakeboard fahren lernen | Sitzstart | Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: '',
      board: '',
      jump: false,
      degree: 0,
    },
    category: 'start',
    level: 2,
    name: 'Mattenstart',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'PDL4hAbgatA',
        start: 0,
        title: 'Mattenstart Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: '',
      board: '',
      jump: true,
      degree: 0,
    },
    category: 'start',
    level: 3,
    name: 'Jump Start',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'Vx75FtYU1_o',
        start: 0,
        title: 'Sprungstart Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
    ],
  },
  {
    attributes: {
      rotate: '',
      board: '',
      jump: true,
      degree: 0,
    },
    category: 'start',
    level: 4,
    name: 'Nollie Start',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: '8YF6o2MQS1A',
        start: 0,
        title: 'Nollie Sprungstart Wakeboard Tutorial',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: '3EKWY9v501c',
        start: 0,
        title: 'Wakeboard Trick Anfänger Nollie Sprungstart (GER)',
        lang: 'de',
        channel: 'how2wake',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'msUCmLGOZCI',
        start: 0,
        title: 'Cable Wakeboard Tricktip Nollie Jumpstart (ENG)',
        lang: 'en',
        channel: 'how2wake',
      },
    ],
  },
  {
    attributes: {
      rotate: '',
      board: '',
      jump: true,
      degree: 0,
    },
    category: 'start',
    level: 4,
    name: 'Raley Start',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'sxDKfyS15CI',
        start: 0,
        title: 'Raley Start | Wakeboard Tutorial [GER]',
        lang: 'de',
        channel: 'WakeboomerTV',
      },
      {
        type: 'video',
        platform: 'youtube',
        id: 'niKIxHH24Ps',
        start: 0,
        title: 'Raley Start | Wakeboard Tutorial [ENG]',
        lang: 'en',
        channel: 'WakeboomerTV',
      },
    ],
  },

  // Placeholder
  // {
  //   attributes: {
  //     rotate: '',
  //     board: '',
  //     jump: true,
  //     degree: 0,
  //   },
  //   category: 'start',
  //   name: '',
  //   requirements: [],
  //   resources: [
  //     {
  //       type: 'video',
  //       platform: 'youtube',
  //       id: '',
  //       start: 0,
  //       title: '',
  //       lang: 'de',
  //       channel: 'WakeboomerTV',
  //     },
  //   ],
  // },

  // Ollie (WIP)
  {
    attributes: {
      rotate: false,
      board: 'HS',
      jump: true,
      degree: 0,
    },
    category: 'ollie',
    level: 1,
    name: 'Ollie',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'csBs5at14nA',
        start: 20,
        title: 'Ollie Wakeboard Tutorial [GER]',
        lang: 'de',
      },
    ],
  },
  {
    attributes: {
      rotate: 'BS',
      board: 'TS',
      jump: true,
      degree: 180,
    },
    category: 'ollie',
    level: 2,
    name: 'Ollie HS FS 180',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: 'FUp1gZrz2rE',
        start: 20,
        title: 'Ollie HS FS 180 Wakeboard Tutorial [GER]',
        lang: 'de',
      },
    ],
  },
  {
    attributes: {
      rotate: 'BS',
      board: 'HS',
      jump: true,
      degree: 180,
    },
    category: 'ollie',
    level: 3,
    name: 'Ollie HS BS 180',
    requirements: [],
    resources: [
      {
        type: 'video',
        platform: 'youtube',
        id: '4Gvq6yTnHHc',
        start: 20,
        title: 'Ollie HS BS 180 Wakeboard Tutorial [GER]',
        lang: 'de',
      },
    ],
  },
];

export default skills;
